stateDiagram-v2
    [*] --> InitActor
    
    state InitActor {
        [*] --> GetWhisperReferences
        GetWhisperReferences --> InitializeVAD
        InitializeVAD --> InitializeBuffers
        InitializeBuffers --> ResetState
        ResetState --> [*]
    }
    
    InitActor --> ProcessAudioChunk
    
    state ProcessAudioChunk {
        [*] --> PrependRemainder
        PrependRemainder --> ComputeVADWindow
        ComputeVADWindow --> SaveRemainder
        SaveRemainder --> CheckVADEvents
    }
    
    CheckVADEvents --> SpeakingStarted: VAD Controller 'start'
    CheckVADEvents --> PrependRemainder: Continue
    
    state SpeakingStarted {
        [*] --> IsRecording
        [*] --> IsNotRecording
        IsNotRecording --> RecordingStateIsReset: Reset State
        RecordingStateIsReset --> IsRecording: Start Recording
    }
    
    SpeakingStarted --> Recording
    
    state Recording {
        [*] --> AppendToBuffer
        AppendToBuffer --> CheckPause
        CheckPause --> AppendToBuffer: Continue
        CheckPause --> BackgroundOffload: Pause + duration > 3s
        
        state BackgroundOffload {
            [*] --> CopyToTempBuffer
            CopyToTempBuffer --> EmptyAudioBuffer
            EmptyAudioBuffer --> OffloadTranscribe
            OffloadTranscribe --> ResetVADWorker
            ResetVADWorker --> [*]
        }
        
        BackgroundOffload --> AppendToBuffer
    }
    
    Recording --> FinalizeSpeech: VAD Controller 'end'
    
    state FinalizeSpeech {
        [*] --> GatherPendingTasks
        GatherPendingTasks --> TranscribeTail
        TranscribeTail --> ConstructFinalText
        ConstructFinalText --> ResetSessionState
        ResetSessionState --> ReturnResult
        ReturnResult --> [*]
    }
    
    FinalizeSpeech --> ProcessAudioChunk